package org.scorpion.cipher.security.symmetry;

import java.security.Key;

import org.scorpion.cipher.security.IScorpionAsymmetry;
import org.scorpion.cipher.security.IScorpionSymmetry;
import org.scorpion.cipher.security.configuration.AbsScorpionCipherConfiguration;
import org.scorpion.cipher.security.configuration.Constant;
import org.scorpion.cipher.security.configuration.ScorpionCipherInfo;
import org.scorpion.cipher.security.util.ScorpionCipherManagerUtil;

public class ScorpionSymmetryFactory {
	
	public static IScorpionSymmetry getCigher(String name){
		AbsScorpionCipherConfiguration ScorpionCipherConfiguration = AbsScorpionCipherConfiguration.getInstance();
		ScorpionCipherInfo info = ScorpionCipherConfiguration.getType(name);
		
		if(info == null || !Constant.CipherType.SYMMETRY.equals(info.getType())){
			return null;
		}
		
		IScorpionSymmetry ScorpionSymmetry = null;
		if(Constant.SymmetryAlgorithm.DES.equals(info.getAlgorithm())){
			ScorpionSymmetry = new ScorpionCipherDES(info);
		}
		
		return ScorpionSymmetry;
	}
	
	public static void main(String[] args) throws Exception{
//		AbsScorpionCipherConfiguration ScorpionCipherConfiguration = AbsScorpionCipherConfiguration.getInstance();
//		ScorpionCipherConfiguration.loadCipherConfiguration();
//		IScorpionSymmetry ScorpionSymmetry = ScorpionSymmetryFactory.getCigher("DES");
//		Key key = ScorpionSymmetry.generateSecretKey();
//		System.out.println(Base64.encodeBase64String(ScorpionSymmetry.generateSecretKeyEncoded()).getBytes("UTF-8").length);
//		System.out.println(Base64.encodeBase64String(ScorpionSymmetry.generateSecretKeyEncoded()).getBytes("UTF-8").length);
//		System.out.println(Base64.encodeBase64String(ScorpionSymmetry.generateSecretKeyEncoded()).getBytes("UTF-8").length);
//		byte[] byt = ScorpionSymmetry.encrypt(key, "测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据".getBytes("UTF-8"));
////		String str = new String(ScorpionSymmetry.decrypt(key, byt), "UTF-8");
//		byt = "测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据测试加密数据".getBytes("UTF-8");
//		System.out.println(Base64.encodeBase64String(byt));
//		System.out.println(ScorpionCipherUtil.bytesToHexString(ScorpionCipherUtil.MD5Encoding(byt)));
//		System.out.println(ScorpionCipherUtil.bytesToHexString(ScorpionCipherUtil.MD5Encoding(byt)));
		AbsScorpionCipherConfiguration ScorpionCipherConfiguration = AbsScorpionCipherConfiguration.getInstance();
		ScorpionCipherConfiguration.loadCipherConfiguration();
		IScorpionSymmetry ScorpionSymmetry = ScorpionSymmetryFactory.getCigher("DES");
		String key1 = "cVs14FPWEk7DFJeLkRe3pcMzU54akXG1/Yl7qZ7anWWt90hvXuPJEx3WtpiiVjrHtcux9La/+4QWIfvLq0khDXujCKP8NKUvmBz5Jeu1tDvxoUW9SfRK59LnGucdlrVHIYsT7ByhrOQn4j0TIYs6KASYp1cwzCFX5v9BgHZlo4IjMLhkj93BX1w096nOhEsqsIt8Tig+mKdpx+WofnI2jrv9KcGm30cg5m8OzBK5LAyo0FYg17o3xBUSVuFHRzbQVC8RJ3Jcf/maYyx9DHJ1Ubo1mOq4y3STWq5f/Y+WKnIdPtPeg7BRDiTmah/CoLjcLFuH4ATKjDR6sbsbwRmgOQ==";
		String key2 = "rGxITAOtosUsV4mpz+U6/A2FQOUHNK+nEhJF61a5S/hrA0n/ewTOjlJLCZp46oql53AvmrKjy/UT1AookmPiIDqvZLGMTxlpFm7Hy1CH9EF9OGQc80Nb1/9tgTwrpPcMYuiBankiqH/9Jgg3DrFbfsvQC4Wgj+gGMig+Jin6AzF6Ts3FQ8AVkvqYjPBvzqwFmYUKklErA8JOtpRFlqOMxAw4wrDPOadISgXQUo0qit4eIhFkIjz/iJDPTKLIMuJhnppFRdjE36ZY6wVtWlc1sDoqPXa7/9CPLrGxKLkHvXjlyaecuSAiCqD7m+PrBiCAaaK7aN3p9QBg13vVXMKvvw==";
		Key key = ScorpionSymmetry.generateSecretKey();
		IScorpionAsymmetry asymmetryCurrent = ScorpionCipherManagerUtil.getInstanceAsymmetry(null);
		key1 = ScorpionCipherManagerUtil.decryptAsymmetry(asymmetryCurrent, key1);
		key1 = ScorpionCipherManagerUtil.decryptAsymmetry(asymmetryCurrent, key2);
		
//		Key key = ScorpionSymmetry.byteToSecretKey(Base64.decodeBase64(key1));
		String data = ScorpionCipherManagerUtil.encryptSymmetry(ScorpionSymmetry, key, 
				"123456789");
		System.out.println(data);
	}

}
